/**
 * Missing Documents Agent - Identifies and requests missing claim documents
 *
 * Checks uploaded documents against the required set for this claim type,
 * identifies what's missing, and generates follow-up emails requesting
 * the missing items. Handles automatic follow-up scheduling.
 *
 * Location: apps/api/src/services/agents/documents.agent.ts
 */
import { generateContent } from './gemini-client';
import { executeTool } from './tools';
import type { BaseAgent, AgentContext, AgentResult } from './types';

const SYSTEM_PROMPT = `You are the FreightClaims Missing Documents Agent. You specialize in identifying what documents are required for freight claims and drafting professional follow-up requests.

Standard required documents by claim type:
- ALL claims: Bill of Lading (BOL), Proof of Delivery (POD), Commercial Invoice
- Damage: Damage photos, Inspection report (if available)
- Shortage: Delivery receipt showing short count, Packing list
- Loss: Proof of pickup, Trace documentation from carrier
- Concealed damage: Photos, Written statement of discovery date, Inspection report
- Refused: Delivery attempt record, Reason for refusal
- Theft: Police report, Carrier incident report

When drafting request emails, be professional and specific about what's needed and why. Include the claim number and relevant dates. Set reasonable deadlines (7-14 business days).`;

export const documentsAgent: BaseAgent = {
  type: 'documents',
  name: 'Missing Documents Agent',
  description: 'Checks for missing required documents on a claim and generates follow-up request emails.',

  async run(ctx: AgentContext): Promise<AgentResult> {
    const start = Date.now();
    const claimId = ctx.claimId || (ctx.input.claimId as string);

    if (!claimId) {
      return {
        agentType: 'documents',
        status: 'failed',
        result: 'No claim ID provided',
        summary: 'Cannot check documents without a claim ID',
      };
    }

    // Step 1: Get the claim details
    const claimResult = await executeTool('getClaim', { claimId }, ctx);
    if (!claimResult.success || !claimResult.data) {
      return {
        agentType: 'documents',
        status: 'failed',
        result: `Claim ${claimId} not found`,
        summary: 'Claim not found in system',
      };
    }

    const claim = claimResult.data as Record<string, unknown>;

    // Step 2: Check which documents are missing
    const missingResult = await executeTool(
      'checkMissingDocuments',
      { claimId, claimType: claim.claimType },
      ctx,
    );

    const docStatus = missingResult.data as { uploaded: number; required: number; missing: string[] };

    if (!docStatus.missing || docStatus.missing.length === 0) {
      // All documents present -- add a note and potentially move to compliance check
      await executeTool('addComment', {
        claimId,
        content: 'Document check complete: all required documents are present.',
        type: 'system',
      }, ctx);

      return {
        agentType: 'documents',
        status: 'completed',
        result: 'All required documents are present for this claim.',
        structuredOutput: { docStatus, allPresent: true },
        durationMs: Date.now() - start,
        nextAgent: 'compliance',
        summary: `All ${docStatus.required} required documents accounted for`,
      };
    }

    // Step 3: Generate a professional follow-up email requesting missing docs
    const { text: emailDraft } = await generateContent(
      `Draft a professional email requesting the following missing documents for freight claim ${(claim as any).claimNumber}:

Missing documents: ${docStatus.missing.join(', ')}

Claim details:
- Claim Number: ${(claim as any).claimNumber}
- PRO Number: ${(claim as any).proNumber}
- Claim Type: ${(claim as any).claimType}
- Claim Amount: $${(claim as any).claimAmount}
- Filed: ${(claim as any).filingDate || 'Not yet filed'}

Write a clear, professional email body (no subject line). Include a deadline of 14 business days. Mention that missing documents may delay processing.`,
      { systemInstruction: SYSTEM_PROMPT },
    );

    // Step 4: Create a task for the follow-up
    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + 14);

    await executeTool('createTask', {
      claimId,
      title: `Request missing documents: ${docStatus.missing.join(', ')}`,
      description: `Auto-generated by Documents Agent. Missing: ${docStatus.missing.join(', ')}`,
      priority: docStatus.missing.length > 2 ? 'high' : 'medium',
      dueDate: dueDate.toISOString(),
    }, ctx);

    await executeTool('addComment', {
      claimId,
      content: `Document check: ${docStatus.missing.length} required document(s) missing — ${docStatus.missing.join(', ')}. Follow-up task created.`,
      type: 'system',
    }, ctx);

    return {
      agentType: 'documents',
      status: 'completed',
      result: emailDraft,
      structuredOutput: {
        docStatus,
        allPresent: false,
        missingDocuments: docStatus.missing,
        emailDraft,
      },
      durationMs: Date.now() - start,
      summary: `Found ${docStatus.missing.length} missing documents, drafted follow-up email`,
    };
  },
};
